export enum Activity {
    REGISTER = 'REGISTER',
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    CLICK_CHAT = 'CLICK_CHAT',
    CLICK_CALL = 'CLICK_CALL',
    REDEEM_VOUCHER = 'REDEEM_VOUCHER',

    CHECK_IN = 'CHECK_IN',
    CHECK_OUT = 'CHECK_OUT',
}
