import API_CONSTANTS from "../../../assets-src/constants/api";
const BASE_URL_DW = "";
const BASE_URL_HRV = "";
export const apiPath = {
  GET_USER_POINT: `${BASE_URL_DW}`,
  GET_SET_ACTIVITY: `${BASE_URL_DW}`,

  GET_USER_POINT_HRV: `${BASE_URL_HRV}/${API_CONSTANTS.ID_SHOP}`,
  GET_VOUCHER_INFO: `${BASE_URL_HRV}/${API_CONSTANTS.ID_SHOP}`,
  SET_VOUCHER_CODE: `${BASE_URL_HRV}/${API_CONSTANTS.ID_SHOP}`,
  GET_VOUCHER_USER: `${BASE_URL_HRV}/${API_CONSTANTS.ID_SHOP}`,
  GET_ORDER: `${BASE_URL_HRV}/${API_CONSTANTS.ID_SHOP}`,
  SET_REVIEW: `${BASE_URL_HRV}/${API_CONSTANTS.ID_SHOP}`,
  SET_UPDATE_VIDEO: `${BASE_URL_HRV}`,
  SET_FOLLOW_OA: `${BASE_URL_DW}`,
  SET_SETTING: `${BASE_URL_HRV}/${API_CONSTANTS.ID_SHOP}`,
};
