const API_CONSTANTS = {
  ZALO_GET_NUMBER: "",
  SECRET_KEY: "",
  ZALO_API_KEY: "",
  ZALO_MINI_APP_ID: "",
  ID_SHOP: "",
  NAME_SHOP: "XYZ",
  PHONE_SHOP: "",
  ZALO_NOTI_OPENAPI: "",
  ID_ZALO_OA: "",
  APP_MINI_LOGO: "",
  APPV: 2,
  ICONIC_COLOR: "",
  WEBSITE_URL: "",
  WEBSITE_SALE_URL: "",
  REGISTER_URL: "",
  WEBSITE_STORE: "",
  WEBSITE_TERM: "",
  GOOGLEUTM: "",
};

export default API_CONSTANTS;
